INFO: Setup CEPCSW externals: /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/setup-103.0.2.sh
Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1245, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1285, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.28.00-a8528/x86_64-centos7-gcc11-opt/lib'
which: no ddsim in (/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/podio/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/Gaudi/bin:/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/scripts:/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/contrib/git/bin:/publicfs/cms/user/wanghan/CEPCSW/InstallArea/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/k4EDM4hep2LcioConv/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/GEAR/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/LCIO/bin:/cvmfs/sft.cern.ch/lcg/releases/DD4hep/01.25.01-5059b/x86_64-centos7-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.28.00-a8528/x86_64-centos7-gcc11-opt/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/podio/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/Gaudi/bin:/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/scripts:/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.37-355ed/x86_64-centos7/bin:/cvmfs/sft.cern.ch/lcg/contrib/git/bin:/afs/ihep.ac.cn/soft/CMS/root/5.34.36/root/bin:/afs/ihep.ac.cn/soft/CMS/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin:/cvmfs/cms.cern.ch/common:/afs/ihep.ac.cn/users/w/wanghan/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/remote-cli:/afs/ihep.ac.cn/soft/CMS/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin:/cvmfs/cms.cern.ch/common:/afs/ihep.ac.cn/soft/CMS/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin:/cvmfs/cms.cern.ch/common:/afs/ihep.ac.cn/soft/CMS/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin:/cvmfs/cms.cern.ch/common:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/cvmfs/common.ihep.ac.cn/software/cctools:/opt/puppetlabs/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin/:/usr/local/sbin:/usr/sbin:/cvmfs/common.ihep.ac.cn/software/cctools:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin/:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin/:/cvmfs/common.ihep.ac.cn/software/cctools:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin/)
readlink: missing operand
Try 'readlink --help' for more information.
/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.2/setup-103.0.2.sh: line 126: /cvmfs/sft.cern.ch/lcg/releases/DD4hep/01-12-01-65a08/x86_64-slc6-gcc8-opt/bin/thisdd4hep.sh: Transport endpoint is not connected
build.98.0.0.x86_64-centos7-gcc8-opt/run: line 4: exec: gaudirun.py: not found
